/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.ProductController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Product;

/**
 *
 * @author USER
 */
public class managerview extends javax.swing.JFrame {

    /**
     * Creates new form managerview
     */
    public managerview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jButton5.setText("refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Restockalert");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton8.setText("Addaccount");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)
                        .addGap(43, 43, 43)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        new Addaccount().setVisible(true);
        this.dispose();
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        StringBuilder sb = new StringBuilder();
        try {
            ProductController controller = new ProductController();
            List<Product> products = controller.getAll();
            for (Product p : products) {
                if (p.getQuantity() < 5) {
                    sb.append(p.getId()).append(" - ").append(p.getName()).append(" (").append(p.getQuantity()).append(")").append("\n");
                }
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        if (sb.length() == 0) {
            jTextArea1.setText("No restock alerts");
        } else {
            jTextArea1.setText(sb.toString());
        }
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        loadProducts();
    }
    
private void loadProducts() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID","Name","Category","Price","Quantity"}, 0
        );
        try {
            ProductController controller = new ProductController();
            java.util.List<Product> products = controller.getAll();
            for (Product p : products) {
                model.addRow(new Object[]{
                    p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()
                });
            }
            jTable1.setModel(model);
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton1ActionPerformed_DUP1(java.awt.event.ActionEvent evt) {
    javax.swing.JTextField nameField = new javax.swing.JTextField();
    javax.swing.JTextField categoryField = new javax.swing.JTextField();
    javax.swing.JTextField priceField = new javax.swing.JTextField();
    javax.swing.JTextField qtyField = new javax.swing.JTextField();
    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2));
    panel.add(new javax.swing.JLabel("Name"));     panel.add(nameField);
    panel.add(new javax.swing.JLabel("Category"));  panel.add(categoryField);
    panel.add(new javax.swing.JLabel("Price"));     panel.add(priceField);
    panel.add(new javax.swing.JLabel("Quantity"));  panel.add(qtyField);

    int result = javax.swing.JOptionPane.showConfirmDialog(
        this, panel, "Add Product",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );
    if (result == javax.swing.JOptionPane.OK_OPTION) {
        String name = nameField.getText().trim();
        String category = categoryField.getText().trim();
        double price = Double.parseDouble(priceField.getText().trim());
        int qty = Integer.parseInt(qtyField.getText().trim());
        Product p = new Product(0, name, category, price, qty);
        ProductController controller = new ProductController();
        if (controller.add(p)) {
            loadProducts();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Add failed");
        }
    }
}

private void loadProductsDup1() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID","Name","Category","Price","Quantity"}, 0
    );
    try {
        ProductController controller = new ProductController();
        java.util.List<Product> products = controller.getAll();
        for (Product p : products) {
            model.addRow(new Object[]{
                p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()
            });
        }
        jTable1.setModel(model);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
private void jButton1ActionPerformed_DUP2(java.awt.event.ActionEvent evt) {
    javax.swing.JTextField nameField = new javax.swing.JTextField();
    javax.swing.JTextField categoryField = new javax.swing.JTextField();
    javax.swing.JTextField priceField = new javax.swing.JTextField();
    javax.swing.JTextField qtyField = new javax.swing.JTextField();
    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2));
    panel.add(new javax.swing.JLabel("Name"));     panel.add(nameField);
    panel.add(new javax.swing.JLabel("Category"));  panel.add(categoryField);
    panel.add(new javax.swing.JLabel("Price"));     panel.add(priceField);
    panel.add(new javax.swing.JLabel("Quantity"));  panel.add(qtyField);

    int result = javax.swing.JOptionPane.showConfirmDialog(
        this, panel, "Add Product",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );
    if (result == javax.swing.JOptionPane.OK_OPTION) {
        String name = nameField.getText().trim();
        String category = categoryField.getText().trim();
        double price = Double.parseDouble(priceField.getText().trim());
        int qty = Integer.parseInt(qtyField.getText().trim());
        Product p = new Product(0, name, category, price, qty);
        ProductController controller = new ProductController();
        try {
            if (controller.add(p)) {
                loadProducts();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Add failed");
            }
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}

private void loadProductsDup2() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID","Name","Category","Price","Quantity"}, 0
    );
    try {
        ProductController controller = new ProductController();
        java.util.List<Product> products = controller.getAll();
        for (Product p : products) {
            model.addRow(new Object[]{
                p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()
            });
        }
        jTable1.setModel(model);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        String query = jTextField1.getText().trim();
        if (query.isEmpty()) {
            loadProducts();
            return;
        }
        ProductController controller = new ProductController();
        try {
            try {
                int id = Integer.parseInt(query);
                Product p = controller.getById(id);
                if (p != null) {
                    DefaultTableModel model = new DefaultTableModel(new Object[]{"ID","Name","Category","Price","Quantity"}, 0);
                    model.addRow(new Object[]{p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()});
                    jTable1.setModel(model);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Not found");
                }
            } catch (NumberFormatException nf) {
                String pattern = "%" + query + "%";
                java.util.List<Product> products = controller.findByNameLike(pattern);
                DefaultTableModel model = new DefaultTableModel(new Object[]{"ID","Name","Category","Price","Quantity"}, 0);
                for (Product p : products) {
                    model.addRow(new Object[]{p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()});
                }
                jTable1.setModel(model);
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row to delete");
            return;
        }
        Object idObj = jTable1.getModel().getValueAt(row, 0);
        int id;
        try {
            if (idObj instanceof Number) {
                id = ((Number) idObj).intValue();
            } else {
                id = Integer.parseInt(String.valueOf(idObj));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid ID. Please refresh.");
            return;
        }
        try {
            ProductController controller = new ProductController();
            boolean ok = controller.delete(id);
            if (ok) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(row);
                javax.swing.JOptionPane.showMessageDialog(this, "Deleted");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete failed");
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JTextField nameField = new javax.swing.JTextField();
        javax.swing.JTextField categoryField = new javax.swing.JTextField();
        javax.swing.JTextField priceField = new javax.swing.JTextField();
        javax.swing.JTextField qtyField = new javax.swing.JTextField();
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2));
        panel.add(new javax.swing.JLabel("Name"));
        panel.add(nameField);
        panel.add(new javax.swing.JLabel("Category"));
        panel.add(categoryField);
        panel.add(new javax.swing.JLabel("Price"));
        panel.add(priceField);
        panel.add(new javax.swing.JLabel("Quantity"));
        panel.add(qtyField);
        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Add Product", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (result == javax.swing.JOptionPane.OK_OPTION) {
            String name = nameField.getText().trim();
            String category = categoryField.getText().trim();
            String priceText = priceField.getText().trim();
            String qtyText = qtyField.getText().trim();
            if (name.isEmpty() || category.isEmpty() || priceText.isEmpty() || qtyText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Fill all fields");
                return;
            }
            double price;
            int qty;
            try {
                price = Double.parseDouble(priceText);
                qty = Integer.parseInt(qtyText);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid values");
                return;
            }
            Product p = new Product(0, name, category, price, qty);
            try {
                ProductController controller = new ProductController();
                boolean ok = controller.add(p);
                if (ok) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Added");
                    loadProducts();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Add failed");
                }
            } catch (SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row to edit");
            return;
        }
        Object idObj = jTable1.getModel().getValueAt(row, 0);
        Object nameObj = jTable1.getModel().getValueAt(row, 1);
        Object categoryObj = jTable1.getModel().getValueAt(row, 2);
        Object priceObj = jTable1.getModel().getValueAt(row, 3);
        Object qtyObj = jTable1.getModel().getValueAt(row, 4);
        javax.swing.JTextField nameField = new javax.swing.JTextField(String.valueOf(nameObj));
        javax.swing.JTextField categoryField = new javax.swing.JTextField(String.valueOf(categoryObj));
        javax.swing.JTextField priceField = new javax.swing.JTextField(String.valueOf(priceObj));
        javax.swing.JTextField qtyField = new javax.swing.JTextField(String.valueOf(qtyObj));
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2));
        panel.add(new javax.swing.JLabel("Name"));
        panel.add(nameField);
        panel.add(new javax.swing.JLabel("Category"));
        panel.add(categoryField);
        panel.add(new javax.swing.JLabel("Price"));
        panel.add(priceField);
        panel.add(new javax.swing.JLabel("Quantity"));
        panel.add(qtyField);
        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Edit Product", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (result == javax.swing.JOptionPane.OK_OPTION) {
            try {
                int id = (idObj instanceof Number) ? ((Number) idObj).intValue() : Integer.parseInt(String.valueOf(idObj));
                String name = nameField.getText().trim();
                String category = categoryField.getText().trim();
                double price = Double.parseDouble(priceField.getText().trim());
                int qty = Integer.parseInt(qtyField.getText().trim());
                Product p = new Product(id, name, category, price, qty);
                ProductController controller = new ProductController();
                boolean ok = controller.update(p);
                if (ok) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Updated");
                    loadProducts();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Update failed");
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid values");
            }
        }
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        new login().setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
