/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.ProductController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Product;

/**
 *
 * @author USER
 */
public class salesrepview extends javax.swing.JFrame {

    /**
     * Creates new form salesrepview
     */
    public salesrepview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(42, 42, 42)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        loadProducts();
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        String query = jTextField1.getText().trim();
        if (query.isEmpty()) {
            loadProducts();
            return;
        }
        ProductController controller = new ProductController();
        try {
            try {
                int id = Integer.parseInt(query);
                Product p = controller.getById(id);
                if (p != null) {
                    DefaultTableModel model = new DefaultTableModel(new Object[]{"ID","Name","Category","Price","Quantity"}, 0);
                    model.addRow(new Object[]{p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()});
                    jTable1.setModel(model);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Not found");
                }
            } catch (NumberFormatException nf) {
                String pattern = "%" + query + "%";
                java.util.List<Product> products = controller.findByNameLike(pattern);
                DefaultTableModel model = new DefaultTableModel(new Object[]{"ID","Name","Category","Price","Quantity"}, 0);
                for (Product p : products) {
                    model.addRow(new Object[]{p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()});
                }
                jTable1.setModel(model);
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadProducts() {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID","Name","Category","Price","Quantity"}, 0);
        try {
            ProductController controller = new ProductController();
            List<Product> products = controller.getAll();
            for (Product p : products) {
                model.addRow(new Object[]{p.getId(), p.getName(), p.getCategory(), p.getPrice(), p.getQuantity()});
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JTextField nameField = new javax.swing.JTextField();
        javax.swing.JTextField categoryField = new javax.swing.JTextField();
        javax.swing.JTextField priceField = new javax.swing.JTextField();
        javax.swing.JTextField qtyField = new javax.swing.JTextField();
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2));
        panel.add(new javax.swing.JLabel("Name"));
        panel.add(nameField);
        panel.add(new javax.swing.JLabel("Category"));
        panel.add(categoryField);
        panel.add(new javax.swing.JLabel("Price"));
        panel.add(priceField);
        panel.add(new javax.swing.JLabel("Quantity"));
        panel.add(qtyField);
        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Add Product", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (result == javax.swing.JOptionPane.OK_OPTION) {
            String name = nameField.getText().trim();
            String category = categoryField.getText().trim();
            String priceText = priceField.getText().trim();
            String qtyText = qtyField.getText().trim();
            if (name.isEmpty() || category.isEmpty() || priceText.isEmpty() || qtyText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Fill all fields");
                return;
            }
            double price;
            int qty;
            try {
                price = Double.parseDouble(priceText);
                qty = Integer.parseInt(qtyText);
            } catch (NumberFormatException nfe) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid values");
                return;
            }
            Product p = new Product(0, name, category, price, qty);
            try {
                ProductController controller = new ProductController();
                boolean ok = controller.add(p);
                if (ok) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Added");
                    loadProducts();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Add failed");
                }
            } catch (SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        new login().setVisible(true);
        this.dispose();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row to delete");
            return;
        }
        Object idObj = jTable1.getModel().getValueAt(row, 0);
        int id;
        try {
            if (idObj instanceof Number) {
                id = ((Number) idObj).intValue();
            } else {
                id = Integer.parseInt(String.valueOf(idObj));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid ID. Please refresh.");
            return;
        }
        try {
            ProductController controller = new ProductController();
            boolean ok = controller.delete(id);
            if (ok) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(row);
                javax.swing.JOptionPane.showMessageDialog(this, "Deleted");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete failed");
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "DB Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesrepview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesrepview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesrepview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesrepview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesrepview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
